# Site
name: "The Beacon"
description: "The Beacon is MCI's newspaper."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
email: "mcibeacon.contact@gmail.com"
instagram: "https://instagram.com/mcibeacon"

include: ["_pages"]
permalink: /:year/:month/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: unknown

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_reverse: true

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
    vendor,
    Gemfile,
    Gemfile.lock,
  ]

keep_files: [CNAME,.git,]


# Add new members to the bottom

authors:
  unknown:
    name: Unknown
    avatar: assets/images/avatars/default.png
    bio: "If you see this, something went wrong, and this page has no author set up for it."
    email: mcibeacon@gmail.com
    instagram: https://instagram.com/mcibeacon
    visible: false

  srao:
    name: "Surbhi Rao"
    bio: "Editor-in-Chief."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  ewong:
    name: "Emma Wong"
    bio: "Copy Editor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  anaing:
    name: "April Naing"
    bio: "Copy Editor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  cmac:
    name: "Cole Anthony Capilongo"
    bio: "Website Team Head."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  ssagar:
    name: "Swamini Sagar"
    bio: "Photography Head."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  mmohammed:
    name: "Muna Mohammed"
    bio: "Publicity and Fundraising Head."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  rmatharu:
    name: "Rhea Matharu"
    bio: "Copy Editor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  smahmud:
    name: "Sanaa Mahmud"
    avatar: assets/images/avatars/sanaa-mahmud.jpg
    bio: "Copy Editor."
    instagram: https://instagram.com/sanaamahmud_
    visible: true

  hnur:
    name: "Huda Nur"
    bio: "Previous Columnist."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  ntelesford:
    name: "Naomi Telesford"
    bio: "Previous Contributor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  mhutzul:
    name: "Maya Hutzul"
    bio: "Copy Editor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  lli:
    name: "Linda Li"
    bio: "Previous Columnist."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  epark:
    name: "Emily Park"
    avatar: assets/images/avatars/emily-park.jpg
    bio: "Publicity."
    instagram: https://instagram.com/emilypark___
    visible: true

  lbalakrishnan:
    name: "Lavini Balakrishnan"
    avatar: assets/images/avatars/lavini-balakrishnan.jpg
    bio: "Publicity."
    instagram: https://instagram.com/mcibeacon
    visible: true

  ifuse-katayama:
    name: "Ira Fuse-Katayama"
    bio: "Previous Contributor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  nyotis:
    name: "Nicole Yotis"
    bio: "Columnist."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  amehta:
    name: "Ambika Mehta"
    bio: "Previous Contributor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  rsyed:
    name: "Rida Syed"
    bio: "Comics and Illustrations Co-Head."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  ekim:
    name: "Emily Kim"
    bio: "Editor-in-Chief."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  lbaumgart:
    name: "Luke Baumgart"
    bio: "Previous Contributor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  aaden-sabriye:
    name: "Aaliyah Aden-Sabriye"
    bio: "Previous Contributor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: false

  sliao:
    name: "Susanna Liao"
    avatar: assets/images/avatars/susanna-liao.jpg
    bio: "Web Team."
    instagram: https://instagram.com/mcibeacon
    visible: true

  dbrebeanu:
    name: "Diana Brebeanu"
    avatar: assets/images/avatars/diana-brebeanu.jpg
    bio: "Columnist."
    instagram: https://instagram.com/diana.br__
    visible: true

  sranjha:
    name: "Sally Ranjha"
    bio: "Columnist."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  cwei:
    name: "Chloe Wei"
    bio: "Copy Council."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  eca:
    name: "Emil Capilongo Anthony"
    bio: "Copy Council."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  smehta:
    name: "Sia Mehta"
    avatar: assets/images/avatars/sia-mehta.jpg
    bio: "Copy Council."
    instagram: https://instagram.com/siaamehta
    visible: true

  sxiang:
    name: "Skyler Xiang"
    bio: "Copy Council."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/skchuylear
    visible: true

  athakur:
    name: "Advaith Thakur"
    bio: "Web Team."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  ssahni:
    name: "Siya Sahni"
    bio: "Publicity."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  jgordon:
    name: "Jack Gordon"
    bio: "Web Team."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  labeyratne:
    name: "Liren Abeyratne"
    bio: "Web Team."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  abibiresanmi:
    name: "Anjie Bibiresanmi"
    bio: "Publicity Assistant Head."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  rkumar:
    name: "Rohan Kumar"
    bio: "Publicity."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  ksukhija:
    name: "Khushi Sukhija"
    avatar: assets/images/avatars/khushi-sukhija.jpg
    bio: "Comic and Illustrations Co-Head."
    instagram: https://instagram.com/mcibeacon
    visible: true

  rdrummond:
    name: "Riley Drummond"
    bio: "Comic and Illustrations."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  geaton:
    name: "Grace Eaton"
    bio: "Secretary."
    avatar: assets/images/avatars/grace-eaton.jpg
    instagram: https://instagram.com/graceaton_
    visible: true

  sranjha:
    name: "Sally Ranjha"
    bio: "Columnist."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true

  sjain:
    name: "Suryakant Jain"
    bio: "Model United Nations Contributor."
    avatar: assets/images/avatars/default.png
    instagram: https://instagram.com/mcibeacon
    visible: true
