# Site
name: "The Beacon"
description: "The Beacon is MCI's newspaper."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
email: "mcibeacon.contact@gmail.com"
instagram: "https://instagram.com/mcibeacon"

include: ["_pages"]
permalink: /:year/:month/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: unknown

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_reverse: true

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
    vendor,
    Gemfile,
    Gemfile.lock,
  ]

keep_files: [CNAME,.git,]


# Add new members to the bottom

authors:
  unknown:
    name: Unknown
    avatar: assets/images/avatar1.jpg
    bio: "If you see this, something went wrong, and this page has no author set up for it."
    email: mcibeacon@gmail.com
    instagram: https://instagram.com/mcibeacon

  srao:
    name: "Surbhi Rao"
    #avatar: assets/images/surbhi-rao.jpg
    bio: "Editor-in-Chief."
    instagram: https://instagram.com/mcibeacon

  ewong:
    name: "Emma Wong"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  anaing:
    name: "April Naing"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  cmac:
    name: "Cole Anthony Capilongo"
    bio: "Website Team Head."
    instagram: https://instagram.com/mcibeacon

  ssagar:
    name: "Swamini Sagar"
    bio: "Photography Head."
    instagram: https://instagram.com/mcibeacon

  mmohammed:
    name: "Muna Mohammed"
    bio: "Publicity and Fundraising Head."
    instagram: https://instagram.com/mcibeacon

  rmatharu:
    name: "Rhea Matharu"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  smahmud:
    name: "Sanaa Mahmud"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  hnur:
    name: "Huda Nur"
    bio: "Previous Columnist."
    instagram: https://instagram.com/mcibeacon

  ntelesford:
    name: "Naomi Telesford"
    bio: "Previous Contributor."
    instagram: https://instagram.com/mcibeacon

  mhutzul:
    name: "Maya Hutzul"
    bio: "Copy Editor."
    instagram: https://instagram.com/mcibeacon

  lli:
    name: "Linda Li"
    bio: "Previous Columnist."
    instagram: https://instagram.com/mcibeacon

  epark:
    name: "Emily Park"
    bio: "Publicity."
    instagram: https://instagram.com/mcibeacon

  lbalakrishnan:
    name: "Lavini Balakrishnan"
    bio: "Publicity."
    instagram: https://instagram.com/mcibeacon

  ifuse-katayama:
    name: "Ira Fuse-Katayama"
    bio: "Previous Contributor."
    instagram: https://instagram.com/mcibeacon

  nyotis:
    name: "Nicole Yotis"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon

  amehta:
    name: "Ambika Mehta"
    bio: "Previous Contributor."
    instagram: https://instagram.com/mcibeacon

  rsyed:
    name: "Rida Syed"
    bio: "Comics and Illustrations Co-Head."
    instagram: https://instagram.com/mcibeacon

  ekim:
    name: "Emily Kim"
    bio: "Editor-in-Chief."
    instagram: https://instagram.com/mcibeacon

  lbaumgart:
    name: "Luke Baumgart"
    bio: "Previous Contributor."
    instagram: https://instagram.com/mcibeacon

  aaden-sabriye:
    name: "Aaliyah Aden-Sabriye"
    bio: "Previous Contributor."
    instagram: https://instagram.com/mcibeacon

  sliao:
    name: "Susanna Liao"
    bio: "Web Team."
    instagram: https://instagram.com/mcibeacon

  dbrebeanu:
    name: "Diana Brebeanu"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon


  sranjha:
    name: "Sally Ranjha"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon

  cwei:
    name: "Chloe Wei"
    bio: "Copy Council."
    instagram: https://instagram.com/mcibeacon

  eca:
    name: "Emil Capilongo Anthony"
    bio: "Copy Council."
    instagram: https://instagram.com/mcibeacon

  smehta:
    name: "Sia Mehta"
    bio: "Copy Council."
    instagram: https://instagram.com/mcibeacon

  sxiang:
    name: "Skyler Xiang"
    bio: "Copy Council."
    instagram: https://instagram.com/mcibeacon

  athakur:
    name: "Advaith Thakur"
    bio: "Web Team."
    instagram: https://instagram.com/mcibeacon

  ssahni:
    name: "Siya Sahni"
    bio: "Publicity."
    instagram: https://instagram.com/mcibeacon

  jgordon:
    name: "Jack Gordon"
    bio: "Web Team."
    instagram: https://instagram.com/mcibeacon

  labeyratne:
    name: "Liren Abeyratne"
    bio: "Web Team."
    instagram: https://instagram.com/mcibeacon

  abibiresanmi:
    name: "Anjie Bibiresanmi"
    bio: "Publicity Assistant Head."
    instagram: https://instagram.com/mcibeacon

  rkumar:
    name: "Rohan Kumar"
    bio: "Publicity."
    instagram: https://instagram.com/mcibeacon

  ksukhija:
    name: "Khushi Sukhija"
    bio: "Comic and Illustrations Co-Head."
    instagram: https://instagram.com/mcibeacon

  rdrummond:
    name: "Riley Drummond"
    bio: "Comic and Illustrations."
    instagram: https://instagram.com/mcibeacon

  geaton:
    name: "Grace Eaton"
    bio: "Secretary."
    instagram: https://instagram.com/mcibeacon

  sranjha:
    name: "Sally Ranjha"
    bio: "Columnist."
    instagram: https://instagram.com/mcibeacon
